// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/account": {
            "put": {
                "description": "update account's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "update account",
                "parameters": [
                    {
                        "description": "account creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateAccountInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful update",
                        "schema": {
                            "$ref": "#/definitions/utils.success_response"
                        }
                    },
                    "400": {
                        "description": "update failure",
                        "schema": {
                            "$ref": "#/definitions/utils.error_response"
                        }
                    }
                }
            },
            "post": {
                "description": "account creation information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "create new account",
                "parameters": [
                    {
                        "description": "account creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AccountCreationInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful create",
                        "schema": {
                            "$ref": "#/definitions/utils.success_response"
                        }
                    },
                    "400": {
                        "description": "create failure",
                        "schema": {
                            "$ref": "#/definitions/utils.error_response"
                        }
                    }
                }
            }
        },
        "/api/v1/account/get": {
            "post": {
                "description": "Get a list of accounts with filtering, sorting, and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Get accounts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records per page",
                        "name": "psize",
                        "in": "query"
                    },
                    {
                        "description": "account'filter option",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/model.AccountFilter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.success_response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Account"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.error_response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.error_response"
                        }
                    }
                }
            }
        },
        "/api/v1/account/{id}": {
            "delete": {
                "description": "delete account information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "delete an account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful delete",
                        "schema": {
                            "$ref": "#/definitions/utils.success_response"
                        }
                    },
                    "400": {
                        "description": "delete failure",
                        "schema": {
                            "$ref": "#/definitions/utils.error_response"
                        }
                    }
                }
            }
        },
        "/api/v1/intern": {
            "put": {
                "description": "update intern's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Intern"
                ],
                "summary": "update intern",
                "parameters": [
                    {
                        "description": "account creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.InternUpdateInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful update",
                        "schema": {
                            "$ref": "#/definitions/utils.success_response"
                        }
                    },
                    "400": {
                        "description": "update failure",
                        "schema": {
                            "$ref": "#/definitions/utils.error_response"
                        }
                    }
                }
            },
            "post": {
                "description": "intern creation information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Intern"
                ],
                "summary": "create new intern-account",
                "parameters": [
                    {
                        "description": "Required: user-name, email, password, student-code",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.InternCreation"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful create",
                        "schema": {
                            "$ref": "#/definitions/utils.success_response"
                        }
                    },
                    "400": {
                        "description": "create failure",
                        "schema": {
                            "$ref": "#/definitions/utils.error_response"
                        }
                    }
                }
            }
        },
        "/api/v1/intern/get": {
            "post": {
                "description": "Get a list of interns with filtering, sorting, and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Intern"
                ],
                "summary": "Get interns",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records per page",
                        "name": "psize",
                        "in": "query"
                    },
                    {
                        "description": "intern'filter option",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/model.InternFilter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.success_response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Intern"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.error_response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.error_response"
                        }
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "Log in using account with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "login by account",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful login",
                        "schema": {
                            "$ref": "#/definitions/utils.success_response"
                        }
                    },
                    "400": {
                        "description": "login failure",
                        "schema": {
                            "$ref": "#/definitions/utils.error_response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Account": {
            "type": "object",
            "properties": {
                "created-at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user-name": {
                    "type": "string"
                }
            }
        },
        "model.AccountCreationInfo": {
            "type": "object",
            "required": [
                "email",
                "password",
                "role",
                "user-name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "role": {
                    "type": "string"
                },
                "user-name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 4
                }
            }
        },
        "model.AccountFilter": {
            "type": "object",
            "properties": {
                "created-at-from": {
                    "type": "string"
                },
                "created-at-to": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "order-by": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user-name": {
                    "type": "string"
                }
            }
        },
        "model.Intern": {
            "type": "object",
            "properties": {
                "account-id": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "date-of-birth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "ojt-semester": {
                    "type": "string"
                },
                "phone-number": {
                    "type": "string"
                },
                "student-code": {
                    "type": "string"
                },
                "user-name": {
                    "type": "string"
                }
            }
        },
        "model.InternCreation": {
            "type": "object",
            "required": [
                "email",
                "password",
                "student-code",
                "user-name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "date-of-birth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "ojt-id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "phone-number": {
                    "type": "string"
                },
                "student-code": {
                    "type": "string",
                    "maxLength": 10,
                    "minLength": 4
                },
                "user-name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 4
                }
            }
        },
        "model.InternFilter": {
            "type": "object",
            "properties": {
                "account-id": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "dob-from": {
                    "type": "string"
                },
                "dob-to": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "ojt-semester": {
                    "type": "string"
                },
                "order-by": {
                    "type": "string"
                },
                "phone-number": {
                    "type": "string"
                },
                "student-code": {
                    "type": "string"
                },
                "user-name": {
                    "type": "string"
                }
            }
        },
        "model.InternUpdateInfo": {
            "type": "object",
            "required": [
                "account-id",
                "email",
                "student-code",
                "user-name"
            ],
            "properties": {
                "account-id": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "date-of-birth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "ojt-id": {
                    "type": "integer"
                },
                "phone-number": {
                    "type": "string"
                },
                "student-code": {
                    "type": "string",
                    "maxLength": 10,
                    "minLength": 4
                },
                "user-name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 4
                }
            }
        },
        "model.LoginForm": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "model.UpdateAccountInfo": {
            "type": "object",
            "required": [
                "email",
                "id",
                "role",
                "user-name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user-name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 4
                }
            }
        },
        "utils.error_response": {
            "type": "object",
            "properties": {
                "log": {
                    "type": "string"
                },
                "message": {},
                "status-code": {
                    "type": "integer"
                }
            }
        },
        "utils.success_response": {
            "type": "object",
            "properties": {
                "data": {},
                "filter": {},
                "message": {
                    "type": "string"
                },
                "paging": {},
                "status": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Intern Resource management system",
	Description:      "A web application to manage interns at the Nextbean Center, designed to oversee their daily tasks and schedules while working at the office. The app aims to streamline the management of internship programs, enabling efficient tracking of intern activities, assignments, and attendance for a well-organized and productive internship experience.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
